apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: inspection-mo-regression-infer-0
  annotations:
    executables.ai.sap.com/description: "Serve a multioutput regression model."
    executables.ai.sap.com/name: inspection-mo-regression-infer-exec
  labels:
    executables.ai.sap.com/id: inspection-mo-regression-infer-0
    scenarios.ai.sap.com/id: inspection-mo-regression-scenario
    ai.sap.com/version: "0.0.1"
spec:
  imagePullSecrets:
    - name: docker-registry-secret
  inputs:
    parameters: []
    artifacts:
      - name: inspectionMoRegressionModel
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      labels:
        ai.sap.com/resourcePlan: infer.s
    spec: '{"predictor": {"containers": [{"name": "kserve-container", "image": "docker.io/zhoudeng2026/restaurant-serve:latest", "ports": [{"containerPort": 9001, "protocol": "TCP"}], "env": [{"name": "STORAGE_URI", "value": "{{inputs.artifacts.inspectionMoRegressionModel}}"}]}]}}'